# Generated by Django 4.0.2 on 2022-02-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_information_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('0.5', 1), ('1', 2), ('1.5', 3), ('2', 4), ('2.5', 5), ('3', 6), ('3.5', 7), ('4', 8), ('4.5', 9), ('5', 10)], default='5', max_length=3),
        ),
    ]
