# Generated by Django 4.0.2 on 2022-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45, verbose_name='user_ID')),
                ('nick_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete or not')),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
