# Generated by Django 4.0.2 on 2022-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usermodel_managers_usermodel_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='bio',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='delete or not'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nick_name',
            field=models.CharField(default=123456, max_length=45),
            preserve_default=False,
        ),
    ]
