# Generated by Django 4.0.2 on 2022-02-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_usermodel_bio_usermodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='nick_name',
        ),
    ]
